# Generated by Django 4.2.2 on 2024-05-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincourse',
            old_name='timeSlot_id',
            new_name='timeSlot',
        ),
    ]
