# Generated by Django 4.2.2 on 2024-05-19 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLogs',
            fields=[
                ('chatLog_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_message', models.CharField(max_length=1000)),
                ('response_message', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDemand',
            fields=[
                ('medicineDemand_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_demand', models.CharField(max_length=300)),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDemandState',
            fields=[
                ('MedicineDemandState_code', models.AutoField(primary_key=True, serialize=False)),
                ('OrderState_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('notify_id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_message', models.CharField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RfidCard',
            fields=[
                ('RfidCard_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Vehicle_status', models.ForeignKey(db_column='VehicleStatus_code', on_delete=django.db.models.deletion.CASCADE, to='backendApp.medicinedemandstate')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('VehicleStatus_code', models.AutoField(primary_key=True, serialize=False)),
                ('VehicleStatus_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='timeSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.mealordertimeslot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetails',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.prescription'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AddField(
            model_name='medicinedemand',
            name='MedicineDemandState',
            field=models.ForeignKey(db_column='MedicineDemandState_code', on_delete=django.db.models.deletion.CASCADE, to='backendApp.medicinedemandstate'),
        ),
        migrations.AddField(
            model_name='medicinedemand',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient'),
        ),
    ]
