# Generated by Django 4.2.2 on 2024-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_rename_timeslot_id_maincourse_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealordertimeslot',
            name='deadlineTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='mealordertimeslot',
            name='endTimes',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='mealordertimeslot',
            name='startTime',
            field=models.TimeField(default='00:00'),
        ),
    ]
