# Generated by Django 4.2.2 on 2024-05-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_chatlogs_medicinedemand_medicinedemandstate_notify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesides',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
