# Generated by Django 4.2.2 on 2024-05-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_delete_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='patient',
        ),
        migrations.CreateModel(
            name='PatientNotifys',
            fields=[
                ('patientNotifys_id', models.AutoField(primary_key=True, serialize=False)),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.notify')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient')),
            ],
        ),
    ]
