# Generated by Django 4.2.2 on 2024-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_remove_notify_patient_patientnotifys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='is_read',
        ),
        migrations.AddField(
            model_name='patientnotifys',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
