# Generated by Django 4.2.1 on 2024-05-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_remove_notify_is_read_patientnotifys_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinedemandstate',
            old_name='MedicineDemandState_code',
            new_name='medicineDemandState_code',
        ),
        migrations.RenameField(
            model_name='medicinedemandstate',
            old_name='OrderState_name',
            new_name='medicineState_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Vehicle_id',
            new_name='vehicle_id',
        ),
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='VehicleStatus_code',
            new_name='vehicleStatus_code',
        ),
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='VehicleStatus_name',
            new_name='vehicleStatus_name',
        ),
        migrations.RemoveField(
            model_name='medicinedemand',
            name='MedicineDemandState',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Vehicle_status',
        ),
        migrations.AddField(
            model_name='medicinedemand',
            name='medicineDemandState',
            field=models.ForeignKey(db_column='medicineDemandState_code', default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.medicinedemandstate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.ForeignKey(db_column='vehicleStatus_code', default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.medicinedemandstate'),
            preserve_default=False,
        ),
    ]
