# Generated by Django 4.2.1 on 2024-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0008_rename_medicinedemandstate_code_medicinedemandstate_medicinedemandstate_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedemand',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
