# Generated by Django 4.2.1 on 2024-05-31 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0009_alter_medicinedemand_review_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidcard',
            old_name='RfidCard_code',
            new_name='rfidCard_code',
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendApp.patient'),
        ),
    ]
